__version__ = "2.5.7"

from .node import (
    NODE_CLASS_MAPPINGS as UTILITY_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as UTILITY_NODE_DISPLAY_NAME_MAPPINGS,
)
from .motion_context_ram import (
    NODE_CLASS_MAPPINGS as MOTION_CONTEXT_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as MOTION_CONTEXT_NODE_DISPLAY_NAME_MAPPINGS,
)
from .extender import (
    NODE_CLASS_MAPPINGS as EXTENDER_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as EXTENDER_NODE_DISPLAY_NAME_MAPPINGS,
)
from .prompt_bridge import (
    NODE_CLASS_MAPPINGS as PROMPT_BRIDGE_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as PROMPT_BRIDGE_NODE_DISPLAY_NAME_MAPPINGS,
)
from .reference_bridge import (
    NODE_CLASS_MAPPINGS as REFERENCE_BRIDGE_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as REFERENCE_BRIDGE_NODE_DISPLAY_NAME_MAPPINGS,
)
from .motion_context_disk import (
    NODE_CLASS_MAPPINGS as MOTION_CONTEXT_DISK_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as MOTION_CONTEXT_DISK_NODE_DISPLAY_NAME_MAPPINGS,
)

NODE_CLASS_MAPPINGS = {
    **UTILITY_NODE_CLASS_MAPPINGS,
    **MOTION_CONTEXT_NODE_CLASS_MAPPINGS,
    **MOTION_CONTEXT_DISK_NODE_CLASS_MAPPINGS,
    **EXTENDER_NODE_CLASS_MAPPINGS,
    **PROMPT_BRIDGE_NODE_CLASS_MAPPINGS,
    **REFERENCE_BRIDGE_NODE_CLASS_MAPPINGS,
}

NODE_DISPLAY_NAME_MAPPINGS = {
    **UTILITY_NODE_DISPLAY_NAME_MAPPINGS,
    **MOTION_CONTEXT_NODE_DISPLAY_NAME_MAPPINGS,
    **MOTION_CONTEXT_DISK_NODE_DISPLAY_NAME_MAPPINGS,
    **EXTENDER_NODE_DISPLAY_NAME_MAPPINGS,
    **PROMPT_BRIDGE_NODE_DISPLAY_NAME_MAPPINGS,
    **REFERENCE_BRIDGE_NODE_DISPLAY_NAME_MAPPINGS,
}

WEB_DIRECTORY = "./web"

__all__ = [
    "__version__",
    "NODE_CLASS_MAPPINGS",
    "NODE_DISPLAY_NAME_MAPPINGS",
    "WEB_DIRECTORY",
]
